In [3]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import torch
import torch.nn as nn
class Linear(nn.Module):
    def __init__(self, n_inputs, n_outputs):
        super().__init__()
        self.n_inputs = n_inputs
        self.n_outputs = n_outputs
        self.W = nn.Parameter(torch.Tensor(self.n_inputs, self.n_outputs))
        self.init_weights()
    def init_weights(self):
        for param in self.parameters():
            nn.init.uniform_(param, -0.1, 0.1)
    def forward(self, x):
        return x @ self.W

In [5]:
class Conv1D(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_width):
        """ kernel_width harus ganjil """
        super(Conv1D, self).__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_width = kernel_width
        self.pad_size = (self.kernel_width - 1) // 2
        self.kernel = Linear(kernel_width * in_channels, out_channels)
    def forward(self, x):
        # padding
        x = nn.functional.pad(x, (self.pad_size, self.pad_size), "constant", 0)
        l = []
        for i in range(self.pad_size, x.shape[2] - self.pad_size):
            patch = x[:, :, i - self.pad_size: i + self.pad_size + 1]
            patch = patch.reshape(x.shape[0], self.in_channels * self.kernel_width)
            l.append(self.kernel(patch))
            
        return torch.stack(l, dim=2)


Torch.stack

In [6]:
x = torch.tensor([[1,2,3], [4,5,6]])
print(torch.stack([x, x], dim=1))
""" tensor([[[1, 2, 3],
         [1, 2, 3]],
        [[4, 5, 6],
         [4, 5, 6]]])
         """
print(torch.stack([x, x], dim=2))
"""tensor([[[1, 1],
         [2, 2],
         [3, 3]],
        [[4, 4],
         [5, 5],
         [6, 6]]])"""
print(torch.stack([x, x], dim=0))

"""tensor([[[1, 2, 3],
         [4, 5, 6]],
        [[1, 2, 3],
         [4, 5, 6]]])"""


tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6]]])
tensor([[[1, 1],
         [2, 2],
         [3, 3]],

        [[4, 4],
         [5, 5],
         [6, 6]]])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


'tensor([[[1, 2, 3],\n         [4, 5, 6]],\n        [[1, 2, 3],\n         [4, 5, 6]]])'

In [18]:
seq = torch.tensor([[[1.,2.,3.,4.,5.], [5.,4.,3.,2.,1.]],
[[1.,2.,3.,4.,5.], [5.,4.,3.,2.,1.]]])

print(seq.shape) 

conv = Conv1D(2, 7, 3)
 # torch.size([2, 2, 5])
print(conv(seq).shape) 

torch.Size([2, 2, 5])
tensor([[[ 0.5090,  0.2823,  0.2535,  0.2247,  0.1547],
         [-0.2372, -0.1277, -0.3058, -0.4839, -0.7776],
         [ 0.2449,  0.4284,  0.1594, -0.1096, -0.0069],
         [ 0.1822,  0.0292,  0.1593,  0.2893,  0.0346],
         [-0.3418, -0.3281, -0.0197,  0.2888,  0.3753],
         [ 0.2777,  0.4209,  0.2498,  0.0786, -0.1206],
         [ 0.1046, -0.1358, -0.2450, -0.3543,  0.0033]],

        [[ 0.5090,  0.2823,  0.2535,  0.2247,  0.1547],
         [-0.2372, -0.1277, -0.3058, -0.4839, -0.7776],
         [ 0.2449,  0.4284,  0.1594, -0.1096, -0.0069],
         [ 0.1822,  0.0292,  0.1593,  0.2893,  0.0346],
         [-0.3418, -0.3281, -0.0197,  0.2888,  0.3753],
         [ 0.2777,  0.4209,  0.2498,  0.0786, -0.1206],
         [ 0.1046, -0.1358, -0.2450, -0.3543,  0.0033]]],
       grad_fn=<StackBackward0>)


In [20]:
seq = torch.tensor([[1,2,3,],[4,5,6]])

# print(seq.shape) 

conv = Conv1D(2, 2, 3)
 # torch.size([2, 2, 5])
print(conv(seq).shape) 

IndexError: tuple index out of range