File ini untuk explore cara pake torch

In [2]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


Cara pake tensor di torch, operation basic, dll

In [4]:
import torch

# Create a 3D tensor of size (3, 4, 5)
X = torch.arange(3*4*5).reshape(3, 4, 5)
print(X)
# Example 1: Scalar value at index (1, 2, 3)
scalar_value = X[1, 2, 3]
print("Scalar value at index (1, 2, 3):", scalar_value)

# Example 2: 2D slice at index 1 (which gives a matrix of size (4, 5))
matrix_slice = X[1]
print("2D slice at index 1:\n", matrix_slice)

# Example 3: Complex slice X[1, :, 2:4] (which gives a 2D slice of size (4, 2))
complex_slice = X[1, :, 2:4]
print("Complex slice X[1, :, 2:4]:\n", complex_slice)


tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
Scalar value at index (1, 2, 3): tensor(33)
2D slice at index 1:
 tensor([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]])
Complex slice X[1, :, 2:4]:
 tensor([[22, 23],
        [27, 28],
        [32, 33],
        [37, 38]])


In [5]:
# broadcasting rule problem 
X = torch.randn((4,1))
print(f"ini X\n {X}")

Y = torch.randn((4,))
print(f"ini Y\n {Y}")

operasi = (X+Y)
print(f"X+Y\n {operasi}")
print(operasi.shape)

"""
    Seharusnya pake yang X kalo mau column vector dan Y klo mau row vector dan klo mau operasi
    harus sama sama row atau sama sama col 
"""

ini X
 tensor([[-1.5865],
        [-1.0122],
        [-0.4547],
        [-0.3462]])
ini Y
 tensor([0.4134, 0.3966, 0.2922, 2.0167])
X+Y
 tensor([[-1.1731, -1.1899, -1.2944,  0.4302],
        [-0.5988, -0.6156, -0.7201,  1.0045],
        [-0.0413, -0.0580, -0.1625,  1.5620],
        [ 0.0672,  0.0504, -0.0540,  1.6705]])
torch.Size([4, 4])


In [10]:
# reduction operation in tensor
a = torch.randn((2,3))
print(a)
# contoh 
# tensor([[-2.2068,  0.5512,  0.1931],
#        [ 0.7843,  0.9264,  1.9125]]) 
s1 = torch.sum(a, dim=0) # sum dimensi ke 0 (-2.068+0.7843) dan seterusnya
print(s1)
s1 = torch.sum(a, dim=1)  # sum dimensi ke 1 (-2.068+0.5512+0.1931) dan 0.7843 +  0.9264 + 1.9125
print(s1)
s1 = torch.sum(a)
print(s1) # klo tanpa dimensi sum semua angka


tensor([[-2.2068,  0.5512,  0.1931],
        [ 0.7843,  0.9264,  1.9125]])
tensor([-1.4225,  1.4775,  2.1055])
tensor([-1.4626,  3.6231])
tensor(2.1605)


In [11]:
import heapq

heap = []
heapq.heappush(heap, 10)
heapq.heappush(heap, -10)
heapq.heappush(heap, 0)

print(heap)  # Output: [-10, 10, 0]


[-10, 10, 0]
